### ISSUE TITLE
TracingCommandGateway clean up suggestions

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#10]
The private `sendWithSpan` method uses a wrong parameter order for the `SpanConsumer` functional interface.
Specifically, I am talking about the consumer parameter, where parent and child places are mixed

Also, there is no need for passing `Tracer` instance there since it's a field.

**Comment by Sam-Kruglov** [comment]
Specifically, I am talking about the consumer parameter, where parent and child places are mixed

**Comment by smcvb** [comment]
Thanks for filing this issue @Sam-Kruglov. My gut tells me however that this are clean up suggestions and not per say bugs/issue with the implementation you've encountered, correct?

If you did encounter usability issue due to these concerns you raise, it would be beneficial to provide a thorough explanation on this when you create a ticket.

Additionally, I've made some adjustments to the description you've provided to clarify what I feel your intent was with describing the ticket. For future occurrences of issues you create, I'd like to ask you to be as specific as possible, using code blocks, links, line numbers etc. And, if you have a suggested solution, sharing that is obviously also very helpful.

To get back to the question I have at hand though - do the concerns you point out impact the usability of the `TracingCommandGateway` at this point in time?

**Comment by Sam-Kruglov** [comment]
Sorry for the unclear explanation.
Main concern is that in a lambda a child span parameter is actually named parent, and where it's a parent, it's named as a child... Hard to explain from phone, I will come back to it

**Comment by dzonekl** [comment]
So nice when people have a critical look at the code, it always improves :-) Thanks @Sam-Kruglov !

**Comment by smcvb** [comment]
Exactly @dzonekl, we very much value any contributions. So no need to excuse yourself @Sam-Kruglov, your input is very much valued! :-)
