### ISSUE TITLE
Any example for integrating with skywalking?

### ISSUE THREAD

**Issue by fff** [AxonFramework/extension-tracing#119]
### Feature Description

Integrate tracing with apache-skywalking

### Current Behaviour

Opentracing is no longer active, and skywalking is only supporting opentracing 0.30; 
Extension-tracing is built with opentracing >=0.33?

### Wanted Behaviour

Integrate with skywalking directly

### Possible Workarounds

No idea

**Comment by smcvb** [comment]
I would like to point out @fff that _any_ of Axon's issue trackers are not intended to ask for samples.
The issue tracker is intended for features, enhancements and bugs which would take effect on a project.
Sample implementations typically do not tag along in that category.

Noted, there is a [basic sample module](https://github.com/AxonFramework/extension-tracing/tree/master/tracing-axon-example) in this project.
If you have the desire to provide a pull request to adjust that, you can be my guest.
Otherwise, I would like to point out that questions like these should be pointed towards AxonIQ's [forum](https://discuss.axoniq.io/) or to StackOverflow with the `axon` tag.

To answer one of your other questions:

> Extension-tracing is built with opentracing >=0.33?

This extension is based on `opentracing-spring-tracer-configuration-starter` 0.4.0, which in turn uses `io.opentracing` version 0.33.0 (as can be seen [here](https://github.com/opentracing-contrib/java-spring-tracer-configuration/blob/f7efc7bc0bcfd599fe7566c9efb1235498bd7e40/pom.xml#L65).

Lastly, I would argue that "no longer active" is putting it harshly. 
It's been merged with OpenCensus into [OpenTelemetry](https://opentelemetry.io/), so it'll definitely live on.

At the time we haven't looked into upgrading the Tracing Extension to use OpenTelemetry yet.
The main concern, for the time being, is that it simply is not a backwards-compatible adjustment at all.
Hence, any users upgrading from Tracing Extension 4.4 to a newer version using OpenTelemetry would very likely break their set up entirely.
This is something we do not aim for, *at all*, at AxonIQ.

**Comment by smcvb** [comment]
Assuming to have clarified sufficiently that such an issue does not belong on the GitHub issue tracker.
Please try out the [forum](https://discuss.axoniq.io/) as mentioned before.
For now, I will close this issue under the tag `question`.

**Comment by fff** [comment]
Sorry for the improper title, my main idea is inspired by "There are other supported tracers that can be used: LightStep, Instana, Apache SkyWalking..." in the reference doc. It appears that SkyWalking is not simply supported by extension-tracing. Thank you for the answering, it helps anyway.

**Comment by smcvb** [comment]
Aaah alright, I catch your drift right now @fff. My apologies for the wrong interpretation.
You have likely hit a discrepancy between the reference guide and the actual implementation here.

If anything in the reference guide is _ever_ out of order or unclear, you can drop features/enhancements/bugs under [this](https://github.com/AxonIQ/reference-guide) GitHub project on the matter.
To be honest, I am anticipating the page in the reference guide will be updated as soon as this extension leverages OpenTelemetry.
I find it hard to deduce when that's going to happen for the time being though.
