### ISSUE TITLE
SpanUtils#withMessageTags includes payload type name 2 times

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#12]
For commands, we can see both payload type and command name, which is exactly the same thing. I think the if statement should be removed

**Comment by smcvb** [comment]
I understand the suggestion, but the `commandName` is not necessarily identical to the `payloadType` of a `CommandMessage`.
In absence of specification, the `commandName` *will be* identical to the `payloadType`, but you are at leisure to provide a different `commandName`. 

Actually, this situation also holds for the `QueryMessage`, which might have a different `queryName` than the `QueryMessage#getPayloadType()`. 

Regardless, due to the difference in intent of `commandName` and `payloadType`, I will be closing this issue.
