### ISSUE TITLE
Share the traceId between threads

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#13]
I just configured Jaeger, but then decided to also print `traceId` in the application logs.
First, Jaeger has an issue with it: https://github.com/opentracing-contrib/java-spring-jaeger/issues/49

Second, When I use the workaround, I find that only the first log entry contains the `traceId` and others don't. 
I suspect this is due to execution being scattered on different threads.

I would suspect that extending an executor mentioned [here](https://stackoverflow.com/questions/39597545/how-to-pass-the-traceid-spanid-in-threads-used-in-threadpool-in-zipkin) would help.

**Comment by smcvb** [comment]
Thanks for your input on this @Sam-Kruglov, I believe I understand the situation you're in.

I'd like to point that wherever Axon uses an `Executor`, that `Executor` is configurable for the user.
You could actually make your entire application synchronous if you'd want, thus ending up in a situation where you'd never create new threads for different operations.
Whether this is the case for a given user highly depends on their usage of the framework however.

Regardless of the form of your application, if you thus need the `Executor`s to be a `LazyTraceExecutor`s, you have the freedom to configure this yourself.

On a conceptual level, we could enforce such an `Executor` on all the components given the auto wiring of this exact repository.
However, the Tracing Extension is set up to only leverage the Open Tracing API.
This specific `Executor` you're pointing too is not part of the Open Tracing API, but specifically of Spring Cloud Sleuth, which would opt against introduction into this extension.

Added on top of that, since configuring the `Executor`s used by Axon yourself is a possibility, I feel that everything necessary to share the `traceId` between threads is there for your to configure.
As such, I will be closing this issue.
