### ISSUE TITLE
Unnecessary span tags

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#35]
`org.axonframework.extensions.tracing.SpanUtils#withMessageTags` creates some tags for a message:
message id, message type (query/command name or payload class name), payload class name, command name, aggregate id. 
It is added in `TracingCommandGateway` and in `OpenTraceHandlerInterceptor`. 

I think the only useful are the payload class name and aggregate id, others can be removed. In my project, I just included the whole payload into a tag. These messages are supposed to be small anyway.

---
P.S. it itches to make this refactoring inside the interceptor:
```java
private Optional<SpanContext> getParentSpan(Message<?> message) {
    MetaData metaData = message.getMetaData();
    MapExtractor extractor = new MapExtractor(metaData);
    try {
        return Optional.ofNullable(tracer.extract(Format.Builtin.TEXT_MAP, extractor));
    } catch (IllegalArgumentException e) {
        log.error("corrupted parent span", e); //this shouldn't happen but if it does, better print the stacktrace
        return Optional.empty();
    }
}
```

**Comment by smcvb** [comment]
I think "unnecessary" depends on perspective in this case:
 - The `messageId` can be very useful in debugging scenarios if it's been added to log statements. A corresponding tag doesn't sound to awful in that case to me. Added, the `messageId` does not by definition reflect the `aggregateIdentifier`, more so justifying having both.
- The `messageType` field accidentally underwent a chance where it indeed reflected the `messageName` instead. This has been reverted in [this](https://github.com/AxonFramework/extension-tracing/commit/295ff66e778c4116785a51806f455aa9aaa947ce) commit. Lastly, the `messageType` can arguably be beneficial for users, but most upfront in my mind would be to filter on all command messages for example. Again, I don't think this to be too unnecessary.
- Having the `messageName` along side the `payloadType` is I'd say a must, as users are able to define differing command or query names than what the `payloadType` describes. The `@CommandHandler` and `@QueryHandler` annotations have variables so that you are able to deviate from these as well. Due to t his, I think the `messageName` should stay as well. Lastly, the `commandName` field has been renamed to `messageName`, as it should apply for both commands and queries (also adjusted in the aforementioned commit).

Having said that, your issue did spark a last minute check to fine tune the `SpanUtils` class, for which thanks! :-)

Added, your refactor suggestion has also been included, in [this](https://github.com/AxonFramework/extension-tracing/commit/b62011ebd23d1ce15a2a175b1725ea9491439c8e) commit to be exact.

Concluding, I feel all concerns have been addressed. Hence, I will close this issue as resolved.
