### ISSUE TITLE
Copy-pasted method in TracingCommandGateway

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#36]
this method `public <R> CompletableFuture<R> send(Object command)` is exactly the same as defined in the `DefaultCommandGateway`. Why not forward it to the delegate?

**Comment by Sam-Kruglov** [comment]
Also, logger definition uses `LoggerFactory.getLogger(MethodHandles.lookup().lookupClass())` while `DefaultCommandGateway` uses `LoggerFactory.getLogger(DefaultCommandGateway.class)`.  Why don't you guys use Lombok?

**Comment by smcvb** [comment]
**"Duplicate" method remark**
Although the methods look the same, the `send` method called in the `public <R> CompletableFuture<R> send(Object command)` is different then that in the `DefaultCommandGateway`.

Along side that, you are expecting the `delegate` to **always be an instance of** `DefaultCommandGateway`. Chance are high it is, but it is a wrong assumption regardless.
As such, both methods look the same, sadly.

**Logger remark**
The `Logger` instance in the `DefaultCommandGateway` was introduced in 2016, whilst the `TracingCommandGateway` was build early 2019. Although the logger statements look differently, the output will be identical. Added, visions on how to do things chance over time (definitely between 2016 and now). A new approach which renders the same output does not enforce a requirement to chance the entire code base. 

Hence why you will so both approaches throughout the axon projects. I don't feel this to be a major issue though.

**Lombok remark**
We are not using Lombok, and _likely_ will never, because it's just syntactic sugar. Although nice to work with from an end product perspective, it will only enlarge Axon packages without bringing direct value to you, the user. As such we try to steer away from "import madness" so to say and minimize the dependencies we pull in to a minimum.

**Concluding**
I feel all points have been addressed, hence I will close this issue.

**Comment by Sam-Kruglov** [comment]
I see, thanks. 

Lombok doesn't appear in the jar you publish and users won't even notice it unless they download the sources. Lombok FTW

**Comment by smcvb** [comment]
Let's leave Lombok as a matter of taste than. Obviously great that you like it and that it improves your projects. This statement is however not going to adjust our stance on Lombok for the time being; there are more pressing things to implement or debate at AxonIQ rather than syntactic sugar. No offense of course, it's just how things are.
