### ISSUE TITLE
Make global fields of the TracingCommandGateway protected

### ISSUE THREAD

**Issue by Sam-Kruglov** [AxonFramework/extension-tracing#38]
`TracingCommandGateway` has a protected constructor but private `tracer` and `delegate` fields which are required to do anything meaningful in the child class.

**Comment by smcvb** [comment]
I think I catch your drift, as you've extended the `Tracing(Command/Query)Gateway` in your [own](https://github.com/Sam-Kruglov/bike-rental-demo/blob/master/src/main/kotlin/io/axoniq/demo/bikerental/config/tracing/CustomTracingCommandGateway.kt) project. 

However, the fields are currently already accessible if necessary, by setting them yourselves through the `Builder`. Added, I am in the habit of being careful with making fields protected. [This](https://softwareengineering.stackexchange.com/questions/162643/why-is-clean-code-suggesting-avoiding-protected-variables) post explains nicely why.

Because of the above, I think this will bring to little benefit to the Tracing Extension at this point in time. Hence, I will close the issue. 
Everyone should feel free to start the conversation again; future insights can chance everything of course.

**Comment by Sam-Kruglov** [comment]
If my PR #39 gets accepted, I don't really need to extend that anymore. In fact, I am not sure there is a usecase for extending it at all. If it does set up the spans correctly, it's all good. I can imagine I would want to add some custom tags to the span but I can do it through interceptors.
